#!/usr/bin/env python3
"""
dm_gen.py  –  Generate DMData.coe from a human-readable data memory source file.

Input file format  (.dm):
    ; Full-line comment (also # is accepted)
    0xADDR : 0xVALUE   ; optional inline comment
    ADDR   : VALUE      ; address and value may be hex (0x…) or decimal

Comments in the source are preserved in the generated COE output.

Usage:
    python dm_gen.py <source.dm> [output.coe]

    Default output filename: DMData.coe
"""
"""
python tools/im_asm.py tools/test_program.asm IMData.coe
"""

import sys
import re
import os


def parse_int(s: str) -> int:
    s = s.strip()
    if re.fullmatch(r'0[xX][0-9A-Fa-f]+', s):
        return int(s, 16)
    return int(s, 10)


def load_source(path: str) -> dict:
    """Return {addr: (value, comment_or_None)} for every data line in path."""
    memory = {}
    with open(path, encoding='utf-8') as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip('\n').strip()
            if not line or line[0] in (';', '#'):
                continue

            # Separate inline comment
            comment = None
            if ';' in line:
                ci = line.index(';')
                comment = line[ci + 1:].strip() or None
                line = line[:ci].strip()

            if ':' not in line:
                print(f'[WARN] {path}:{lineno}: no ":" found – skipping "{line}"')
                continue

            addr_s, val_s = line.split(':', 1)
            try:
                addr = parse_int(addr_s)
                val  = parse_int(val_s)
            except ValueError as e:
                sys.exit(f'[ERROR] {path}:{lineno}: {e}')

            if not 0 <= addr <= 255:
                sys.exit(f'[ERROR] {path}:{lineno}: address {addr:#04x} out of 0-255 range')
            if not 0 <= val <= 0xFFFF:
                sys.exit(f'[ERROR] {path}:{lineno}: value {val:#06x} out of 0-0xFFFF range')

            memory[addr] = (val, comment)

    return memory


def generate_coe(memory: dict, src_name: str) -> list:
    """Return list of text lines forming a valid Xilinx COE file."""

    # Build flat arrays
    values   = [0]    * 256
    comments = {}                   # addr -> str
    for addr, (val, cmt) in memory.items():
        values[addr] = val
        if cmt:
            comments[addr] = cmt

    out = [
        '; Data Memory initialization  (auto-generated by dm_gen.py)',
        f'; Source: {src_name}',
        ';',
        'memory_initialization_radix=16;',
        'memory_initialization_vector=',
    ]

    i = 0
    while i < 256:
        # --- zero-padding run ---
        if values[i] == 0 and i not in comments:
            j = i + 1
            while j < 256 and values[j] == 0 and j not in comments:
                j += 1
            run  = j - i
            lbl  = f'0x{i:02X}' if run == 1 else f'0x{i:02X}-0x{j - 1:02X}'
            out.append(f'; {lbl}: unused')
            # emit up to 8 zeros per line
            for k in range(0, run, 8):
                chunk_end = min(i + k + 8, j) - 1   # inclusive last address
                size      = chunk_end - (i + k) + 1
                sep       = ';' if chunk_end == 255 else ','
                out.append(', '.join(['0000'] * size) + sep)
            i = j

        # --- annotated / non-zero entry ---
        else:
            cmt_text = f'; 0x{i:02X}: {comments[i]}' if i in comments else f'; 0x{i:02X}'
            out.append(cmt_text)
            sep = ';' if i == 255 else ','
            out.append(f'{values[i]:04X}{sep}')
            i += 1

    return out


def main():
    if len(sys.argv) < 2:
        sys.exit(f'Usage: {sys.argv[0]} <source.dm> [output.coe]')

    src  = sys.argv[1]
    dest = sys.argv[2] if len(sys.argv) > 2 else 'DMData.coe'

    memory = load_source(src)
    lines  = generate_coe(memory, os.path.basename(src))

    with open(dest, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'[OK] {dest}  ({len(memory)} annotated entries, '
          f'{sum(1 for v, _ in memory.values() if v != 0)} non-zero)')


if __name__ == '__main__':
    main()
